version: "2.2"
services:
  server:
    container_name: server
    restart: always
    build: ./squid_games
    ports:
      - "50051:50051"
    networks:
      - grpc

  cliente:
    container_name: cliente
    restart: always
    build: ./cliente
    ports:
      - "8080:8080"
    networks:
      - grpc

networks:
  grpc:
    driver: "bridge"