# pull the official base image
FROM node: alpine

# set working direction
WORKDIR /app

# install application dependencies
COPY package.json ./
COPY package-lock.json ./

RUN npm install
# add app
COPY . ./

# expose port
EXPOSE 3000

# start app
CMD ["npm", "start"]